# This is a basic workflow to help you get started with Actions

name: XyleLedger Coverage

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  coverage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - run: yarn install --dev
    - run: yarn test
    - name: Jest Code Coverage Report
      uses: ziishaned/jest-reporter-action@v0.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-command: "yarn jest --coverage"
    #   uses: romeovs/lcov-reporter-action@v0.2.16
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     lcov-file: $GITHUB_WORKSPACE/coverage/lcov.info

